name: Build and Scan Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build, Scan, and Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t inf8108projet/inf8102project:latest .

    # 4. Scan the Docker image with Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: inf8108projet/inf8102project:latest
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    # 5. Push the Docker image to Docker Hub (if scan passes)
    - name: Push Docker image to Docker Hub
      if: success()
      run: |
        docker push inf8108projet/inf8102project:latest
